### ISSUE TITLE
Export FontCharType in preludes

### ISSUE THREAD

**Issue by thebracket** [thebracket/bracket-lib#114]
FontCharType isn't available in the `rltk::prelude`. It should be.

Additionally: support more conversions.

**Comment by thebracket** [comment]
RLTK does export `FontCharType` in the prelude. The following works with the 0.8.0 from cargo:

```toml
[package]
name = "rltk-test"
version = "0.1.0"
authors = ["Herbert Wolverson <herberticus@gmail.com>"]
edition = "2018"

[dependencies]
rltk = "0.8.0"
```

```rust
use rltk::prelude::*;

struct State {
    glyph : FontCharType
}

impl GameState for State {
    fn tick(&mut self, ctx: &mut Rltk) {
        ctx.cls();
        ctx.set(1,1,RGB::named(RED), RGB::named(BLACK), self.glyph);
    }
}

fn main() -> RltkError {
    let context = RltkBuilder::simple80x50()
        .with_title("Hello RLTK World")
        .with_fps_cap(30.0)
        .build()?;

    rltk::main_loop(context, State{
        glyph : to_cp437('!')
    })
}
```
