### ISSUE TITLE
crash when minimizing the window

### ISSUE THREAD

**Issue by jice-nospam** [thebracket/bracket-lib#81]
I've upgraded bracketlib to version aa37 and still got the error when minimizing the window : 

thread 'main' panicked at 'attempt to divide by zero', C:\.cargo\registry\src\github.com-1ecc6299db9ec823\bracket-terminal-0.7.0\src\bterm.rs:155:17

My cargo.lock:
name = "bracket-lib"
version = "0.7.0"
source = "git+https://github.com/thebracket/bracket-lib#aa37c94de31f9902a0e1c92089f2150e6cc52da7"

**Comment by thebracket** [comment]
Oops; I put a patch into Cargo for the RLTK lib, not the bracket-lib. Try this in your `cargo.toml`:

```toml
# Remove before publish!
[patch.crates-io]
bracket-terminal = { git = "https://github.com/thebracket/bracket-lib/" }
```
